# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MoleculeClassifier(object):
    def setupUi(self, MoleculeClassifier):
        MoleculeClassifier.setObjectName("MoleculeClassifier")
        MoleculeClassifier.setEnabled(True)
        MoleculeClassifier.resize(693, 633)
        self.inputOpt = QtWidgets.QComboBox(MoleculeClassifier)
        self.inputOpt.setGeometry(QtCore.QRect(10, 40, 104, 26))
        self.inputOpt.setObjectName("inputOpt")
        self.label_2 = QtWidgets.QLabel(MoleculeClassifier)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 55, 16))
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(MoleculeClassifier)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 90, 331, 61))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.drawButton = QtWidgets.QPushButton(MoleculeClassifier)
        self.drawButton.setGeometry(QtCore.QRect(30, 160, 132, 32))
        self.drawButton.setObjectName("drawButton")
        self.analyzeButton = QtWidgets.QPushButton(MoleculeClassifier)
        self.analyzeButton.setGeometry(QtCore.QRect(180, 160, 131, 32))
        self.analyzeButton.setObjectName("analyzeButton")
        self.label_5 = QtWidgets.QLabel(MoleculeClassifier)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 128, 16))
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(MoleculeClassifier)
        self.line.setGeometry(QtCore.QRect(10, 320, 674, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(MoleculeClassifier)
        self.label_3.setGeometry(QtCore.QRect(470, 330, 116, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(MoleculeClassifier)
        self.label.setGeometry(QtCore.QRect(140, 330, 45, 16))
        self.label.setObjectName("label")
        self.resultText = QtWidgets.QTextEdit(MoleculeClassifier)
        self.resultText.setEnabled(False)
        self.resultText.setGeometry(QtCore.QRect(10, 350, 331, 83))
        self.resultText.setObjectName("resultText")
        self.wpCheckBox = QtWidgets.QCheckBox(MoleculeClassifier)
        self.wpCheckBox.setEnabled(True)
        self.wpCheckBox.setGeometry(QtCore.QRect(10, 440, 130, 20))
        self.wpCheckBox.setChecked(False)
        self.wpCheckBox.setObjectName("wpCheckBox")
        self.label_4 = QtWidgets.QLabel(MoleculeClassifier)
        self.label_4.setGeometry(QtCore.QRect(20, 470, 102, 16))
        self.label_4.setObjectName("label_4")
        self.fixLabels = QtWidgets.QPlainTextEdit(MoleculeClassifier)
        self.fixLabels.setEnabled(False)
        self.fixLabels.setGeometry(QtCore.QRect(10, 490, 331, 81))
        self.fixLabels.setObjectName("fixLabels")
        self.sendRightButton = QtWidgets.QPushButton(MoleculeClassifier)
        self.sendRightButton.setGeometry(QtCore.QRect(190, 580, 152, 32))
        self.sendRightButton.setObjectName("sendRightButton")
        self.drawMol = QtWidgets.QLabel(MoleculeClassifier)
        self.drawMol.setGeometry(QtCore.QRect(370, 20, 324, 291))
        self.drawMol.setText("")
        self.drawMol.setObjectName("drawMol")
        self.line_2 = QtWidgets.QFrame(MoleculeClassifier)
        self.line_2.setGeometry(QtCore.QRect(348, 8, 20, 591))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.confTable = QtWidgets.QTableWidget(MoleculeClassifier)
        self.confTable.setEnabled(False)
        self.confTable.setGeometry(QtCore.QRect(380, 350, 291, 221))
        self.confTable.setObjectName("confTable")
        self.confTable.setColumnCount(2)
        self.confTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.confTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.confTable.setHorizontalHeaderItem(1, item)
        self.label_6 = QtWidgets.QLabel(MoleculeClassifier)
        self.label_6.setGeometry(QtCore.QRect(140, 10, 60, 16))
        self.label_6.setObjectName("label_6")
        self.infoTable = QtWidgets.QTableWidget(MoleculeClassifier)
        self.infoTable.setEnabled(False)
        self.infoTable.setGeometry(QtCore.QRect(10, 220, 331, 91))
        self.infoTable.setObjectName("infoTable")
        self.infoTable.setColumnCount(2)
        self.infoTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(1, item)
        self.tabWidget = QtWidgets.QTabWidget(MoleculeClassifier)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 111, 21))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(MoleculeClassifier)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MoleculeClassifier)

    def retranslateUi(self, MoleculeClassifier):
        _translate = QtCore.QCoreApplication.translate
        MoleculeClassifier.setWindowTitle(_translate("MoleculeClassifier", "Molecule Classifier"))
        self.label_2.setText(_translate("MoleculeClassifier", "Molecule"))
        self.drawButton.setText(_translate("MoleculeClassifier", "Draw Molecule"))
        self.analyzeButton.setText(_translate("MoleculeClassifier", "Analyze"))
        self.label_5.setText(_translate("MoleculeClassifier", "Molecule information"))
        self.label_3.setText(_translate("MoleculeClassifier", "Results confidence"))
        self.label.setText(_translate("MoleculeClassifier", "Results"))
        self.wpCheckBox.setText(_translate("MoleculeClassifier", "Wrong prediction"))
        self.label_4.setText(_translate("MoleculeClassifier", "Input right labels"))
        self.sendRightButton.setText(_translate("MoleculeClassifier", "Send Right Labels"))
        item = self.confTable.horizontalHeaderItem(0)
        item.setText(_translate("MoleculeClassifier", "Class"))
        item = self.confTable.horizontalHeaderItem(1)
        item.setText(_translate("MoleculeClassifier", "Confidence"))
        self.label_6.setText(_translate("MoleculeClassifier", "Molecule"))
        item = self.infoTable.horizontalHeaderItem(0)
        item.setText(_translate("MoleculeClassifier", "Property"))
        item = self.infoTable.horizontalHeaderItem(1)
        item.setText(_translate("MoleculeClassifier", "Value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MoleculeClassifier", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MoleculeClassifier", "Tab 2"))
