# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page_max_expandable.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 783)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        MainWindow.setMaximumSize(QtCore.QSize(9000, 9000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(900, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 9000))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(900, 600))
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.classification = QtWidgets.QWidget()
        self.classification.setMinimumSize(QtCore.QSize(900, 600))
        self.classification.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.classification.setObjectName("classification")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.classification)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.classification)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.leftSection = QtWidgets.QSplitter(self.splitter)
        self.leftSection.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftSection.setFrameShape(QtWidgets.QFrame.Box)
        self.leftSection.setFrameShadow(QtWidgets.QFrame.Plain)
        self.leftSection.setLineWidth(1)
        self.leftSection.setOrientation(QtCore.Qt.Vertical)
        self.leftSection.setObjectName("leftSection")
        self.label_6 = QtWidgets.QLabel(self.leftSection)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.leftSection)
        self.label_7.setObjectName("label_7")
        self.inputOpt = QtWidgets.QComboBox(self.leftSection)
        self.inputOpt.setObjectName("inputOpt")
        self.label_2 = QtWidgets.QLabel(self.leftSection)
        self.label_2.setObjectName("label_2")
        self.inputString = QtWidgets.QTextEdit(self.leftSection)
        self.inputString.setEnabled(True)
        self.inputString.setReadOnly(False)
        self.inputString.setOverwriteMode(True)
        self.inputString.setAcceptRichText(False)
        self.inputString.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.inputString.setObjectName("inputString")
        self.splitButtonsInput = QtWidgets.QSplitter(self.leftSection)
        self.splitButtonsInput.setOrientation(QtCore.Qt.Horizontal)
        self.splitButtonsInput.setObjectName("splitButtonsInput")
        self.drawButton = QtWidgets.QPushButton(self.splitButtonsInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drawButton.sizePolicy().hasHeightForWidth())
        self.drawButton.setSizePolicy(sizePolicy)
        self.drawButton.setAutoFillBackground(False)
        self.drawButton.setObjectName("drawButton")
        self.analyzeButton = QtWidgets.QPushButton(self.splitButtonsInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyzeButton.sizePolicy().hasHeightForWidth())
        self.analyzeButton.setSizePolicy(sizePolicy)
        self.analyzeButton.setDefault(False)
        self.analyzeButton.setFlat(False)
        self.analyzeButton.setObjectName("analyzeButton")
        self.simButton = QtWidgets.QPushButton(self.splitButtonsInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simButton.sizePolicy().hasHeightForWidth())
        self.simButton.setSizePolicy(sizePolicy)
        self.simButton.setAutoFillBackground(False)
        self.simButton.setObjectName("simButton")
        self.label = QtWidgets.QLabel(self.leftSection)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.resultText = QtWidgets.QTextEdit(self.leftSection)
        self.resultText.setEnabled(True)
        self.resultText.setOverwriteMode(True)
        self.resultText.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.resultText.setObjectName("resultText")
        self.wpCheckBox = QtWidgets.QCheckBox(self.leftSection)
        self.wpCheckBox.setEnabled(True)
        self.wpCheckBox.setChecked(False)
        self.wpCheckBox.setObjectName("wpCheckBox")
        self.label_4 = QtWidgets.QLabel(self.leftSection)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.splitCheckBox = QtWidgets.QSplitter(self.leftSection)
        self.splitCheckBox.setMinimumSize(QtCore.QSize(0, 0))
        self.splitCheckBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitCheckBox.setOrientation(QtCore.Qt.Horizontal)
        self.splitCheckBox.setObjectName("splitCheckBox")
        self.miniSplit1 = QtWidgets.QSplitter(self.splitCheckBox)
        self.miniSplit1.setOrientation(QtCore.Qt.Vertical)
        self.miniSplit1.setObjectName("miniSplit1")
        self.cBox_1 = QtWidgets.QCheckBox(self.miniSplit1)
        self.cBox_1.setEnabled(False)
        self.cBox_1.setChecked(False)
        self.cBox_1.setObjectName("cBox_1")
        self.cBox_4 = QtWidgets.QCheckBox(self.miniSplit1)
        self.cBox_4.setEnabled(False)
        self.cBox_4.setChecked(False)
        self.cBox_4.setObjectName("cBox_4")
        self.cBox_7 = QtWidgets.QCheckBox(self.miniSplit1)
        self.cBox_7.setEnabled(False)
        self.cBox_7.setChecked(False)
        self.cBox_7.setObjectName("cBox_7")
        self.cBox_10 = QtWidgets.QCheckBox(self.miniSplit1)
        self.cBox_10.setEnabled(False)
        self.cBox_10.setChecked(False)
        self.cBox_10.setObjectName("cBox_10")
        self.cBox_13 = QtWidgets.QCheckBox(self.miniSplit1)
        self.cBox_13.setEnabled(False)
        self.cBox_13.setChecked(False)
        self.cBox_13.setObjectName("cBox_13")
        self.cBox_16 = QtWidgets.QCheckBox(self.miniSplit1)
        self.cBox_16.setEnabled(False)
        self.cBox_16.setChecked(False)
        self.cBox_16.setObjectName("cBox_16")
        self.cBox_19 = QtWidgets.QCheckBox(self.miniSplit1)
        self.cBox_19.setEnabled(False)
        self.cBox_19.setChecked(False)
        self.cBox_19.setObjectName("cBox_19")
        self.miniSplit2 = QtWidgets.QSplitter(self.splitCheckBox)
        self.miniSplit2.setOrientation(QtCore.Qt.Vertical)
        self.miniSplit2.setObjectName("miniSplit2")
        self.cBox_2 = QtWidgets.QCheckBox(self.miniSplit2)
        self.cBox_2.setEnabled(False)
        self.cBox_2.setChecked(False)
        self.cBox_2.setObjectName("cBox_2")
        self.cBox_5 = QtWidgets.QCheckBox(self.miniSplit2)
        self.cBox_5.setEnabled(False)
        self.cBox_5.setChecked(False)
        self.cBox_5.setObjectName("cBox_5")
        self.cBox_8 = QtWidgets.QCheckBox(self.miniSplit2)
        self.cBox_8.setEnabled(False)
        self.cBox_8.setChecked(False)
        self.cBox_8.setObjectName("cBox_8")
        self.cBox_11 = QtWidgets.QCheckBox(self.miniSplit2)
        self.cBox_11.setEnabled(False)
        self.cBox_11.setChecked(False)
        self.cBox_11.setObjectName("cBox_11")
        self.cBox_14 = QtWidgets.QCheckBox(self.miniSplit2)
        self.cBox_14.setEnabled(False)
        self.cBox_14.setChecked(False)
        self.cBox_14.setObjectName("cBox_14")
        self.cBox_17 = QtWidgets.QCheckBox(self.miniSplit2)
        self.cBox_17.setEnabled(False)
        self.cBox_17.setChecked(False)
        self.cBox_17.setObjectName("cBox_17")
        self.cBox_20 = QtWidgets.QCheckBox(self.miniSplit2)
        self.cBox_20.setEnabled(False)
        self.cBox_20.setChecked(False)
        self.cBox_20.setObjectName("cBox_20")
        self.miniSplit3 = QtWidgets.QSplitter(self.splitCheckBox)
        self.miniSplit3.setOrientation(QtCore.Qt.Vertical)
        self.miniSplit3.setObjectName("miniSplit3")
        self.cBox_3 = QtWidgets.QCheckBox(self.miniSplit3)
        self.cBox_3.setEnabled(False)
        self.cBox_3.setChecked(False)
        self.cBox_3.setObjectName("cBox_3")
        self.cBox_6 = QtWidgets.QCheckBox(self.miniSplit3)
        self.cBox_6.setEnabled(False)
        self.cBox_6.setChecked(False)
        self.cBox_6.setObjectName("cBox_6")
        self.cBox_9 = QtWidgets.QCheckBox(self.miniSplit3)
        self.cBox_9.setEnabled(False)
        self.cBox_9.setChecked(False)
        self.cBox_9.setObjectName("cBox_9")
        self.cBox_12 = QtWidgets.QCheckBox(self.miniSplit3)
        self.cBox_12.setEnabled(False)
        self.cBox_12.setChecked(False)
        self.cBox_12.setObjectName("cBox_12")
        self.cBox_15 = QtWidgets.QCheckBox(self.miniSplit3)
        self.cBox_15.setEnabled(False)
        self.cBox_15.setChecked(False)
        self.cBox_15.setObjectName("cBox_15")
        self.cBox_18 = QtWidgets.QCheckBox(self.miniSplit3)
        self.cBox_18.setEnabled(False)
        self.cBox_18.setChecked(False)
        self.cBox_18.setObjectName("cBox_18")
        self.label_10 = QtWidgets.QLabel(self.leftSection)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.leftSection)
        self.plainTextEdit_2.setEnabled(False)
        self.plainTextEdit_2.setReadOnly(False)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.sendRightButton = QtWidgets.QPushButton(self.leftSection)
        self.sendRightButton.setObjectName("sendRightButton")
        self.middleSection = QtWidgets.QSplitter(self.splitter)
        self.middleSection.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.middleSection.setOrientation(QtCore.Qt.Vertical)
        self.middleSection.setObjectName("middleSection")
        self.molStrucSplit = QtWidgets.QSplitter(self.middleSection)
        self.molStrucSplit.setFrameShape(QtWidgets.QFrame.Box)
        self.molStrucSplit.setOrientation(QtCore.Qt.Vertical)
        self.molStrucSplit.setObjectName("molStrucSplit")
        self.label_8 = QtWidgets.QLabel(self.molStrucSplit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.drawMol = QLabel_click(self.molStrucSplit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drawMol.sizePolicy().hasHeightForWidth())
        self.drawMol.setSizePolicy(sizePolicy)
        self.drawMol.setText("")
        self.drawMol.setScaledContents(True)
        self.drawMol.setObjectName("drawMol")
        self.simMolSplit = QtWidgets.QSplitter(self.middleSection)
        self.simMolSplit.setFrameShape(QtWidgets.QFrame.Box)
        self.simMolSplit.setOrientation(QtCore.Qt.Vertical)
        self.simMolSplit.setObjectName("simMolSplit")
        self.label_9 = QtWidgets.QLabel(self.simMolSplit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.miniSimMolSplit1 = QtWidgets.QSplitter(self.simMolSplit)
        self.miniSimMolSplit1.setOrientation(QtCore.Qt.Horizontal)
        self.miniSimMolSplit1.setObjectName("miniSimMolSplit1")
        self.similarMol_1 = QLabel_click(self.miniSimMolSplit1)
        self.similarMol_1.setText("")
        self.similarMol_1.setScaledContents(True)
        self.similarMol_1.setObjectName("similarMol_1")
        self.similarMol_2 = QLabel_click(self.miniSimMolSplit1)
        self.similarMol_2.setText("")
        self.similarMol_2.setScaledContents(True)
        self.similarMol_2.setObjectName("similarMol_2")
        self.similarMol_3 = QLabel_click(self.miniSimMolSplit1)
        self.similarMol_3.setText("")
        self.similarMol_3.setScaledContents(True)
        self.similarMol_3.setObjectName("similarMol_3")
        self.miniSimMolSplit2 = QtWidgets.QSplitter(self.simMolSplit)
        self.miniSimMolSplit2.setOrientation(QtCore.Qt.Horizontal)
        self.miniSimMolSplit2.setObjectName("miniSimMolSplit2")
        self.similarMol_6 = QLabel_click(self.miniSimMolSplit2)
        self.similarMol_6.setText("")
        self.similarMol_6.setScaledContents(True)
        self.similarMol_6.setObjectName("similarMol_6")
        self.similarMol_4 = QLabel_click(self.miniSimMolSplit2)
        self.similarMol_4.setText("")
        self.similarMol_4.setScaledContents(True)
        self.similarMol_4.setObjectName("similarMol_4")
        self.similarMol_5 = QLabel_click(self.miniSimMolSplit2)
        self.similarMol_5.setText("")
        self.similarMol_5.setScaledContents(True)
        self.similarMol_5.setObjectName("similarMol_5")
        self.miniSimMolSplit3 = QtWidgets.QSplitter(self.simMolSplit)
        self.miniSimMolSplit3.setOrientation(QtCore.Qt.Horizontal)
        self.miniSimMolSplit3.setObjectName("miniSimMolSplit3")
        self.similarMol_9 = QLabel_click(self.miniSimMolSplit3)
        self.similarMol_9.setText("")
        self.similarMol_9.setScaledContents(True)
        self.similarMol_9.setObjectName("similarMol_9")
        self.similarMol_7 = QLabel_click(self.miniSimMolSplit3)
        self.similarMol_7.setText("")
        self.similarMol_7.setScaledContents(True)
        self.similarMol_7.setObjectName("similarMol_7")
        self.similarMol_8 = QLabel_click(self.miniSimMolSplit3)
        self.similarMol_8.setText("")
        self.similarMol_8.setScaledContents(True)
        self.similarMol_8.setObjectName("similarMol_8")
        self.rightSection = QtWidgets.QSplitter(self.splitter)
        self.rightSection.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rightSection.setFrameShape(QtWidgets.QFrame.Box)
        self.rightSection.setOrientation(QtCore.Qt.Vertical)
        self.rightSection.setObjectName("rightSection")
        self.classProbSplit = QtWidgets.QSplitter(self.rightSection)
        self.classProbSplit.setOrientation(QtCore.Qt.Vertical)
        self.classProbSplit.setObjectName("classProbSplit")
        self.label_5 = QtWidgets.QLabel(self.classProbSplit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.infoTable = QtWidgets.QTableWidget(self.classProbSplit)
        self.infoTable.setEnabled(False)
        self.infoTable.setAutoFillBackground(True)
        self.infoTable.setAlternatingRowColors(True)
        self.infoTable.setShowGrid(True)
        self.infoTable.setObjectName("infoTable")
        self.infoTable.setColumnCount(2)
        self.infoTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.infoTable.setHorizontalHeaderItem(1, item)
        self.infoTable.horizontalHeader().setCascadingSectionResizes(False)
        self.infoTable.horizontalHeader().setDefaultSectionSize(200)
        self.infoTable.horizontalHeader().setStretchLastSection(True)
        self.infoTable.verticalHeader().setCascadingSectionResizes(False)
        self.molInfoSplit = QtWidgets.QSplitter(self.rightSection)
        self.molInfoSplit.setOrientation(QtCore.Qt.Vertical)
        self.molInfoSplit.setObjectName("molInfoSplit")
        self.label_3 = QtWidgets.QLabel(self.molInfoSplit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.confTable = QtWidgets.QTableWidget(self.molInfoSplit)
        self.confTable.setEnabled(False)
        self.confTable.setAutoFillBackground(True)
        self.confTable.setAlternatingRowColors(True)
        self.confTable.setObjectName("confTable")
        self.confTable.setColumnCount(2)
        self.confTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.confTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.confTable.setHorizontalHeaderItem(1, item)
        self.confTable.horizontalHeader().setDefaultSectionSize(200)
        self.confTable.horizontalHeader().setMinimumSectionSize(30)
        self.confTable.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.splitter)
        self.tabWidget.addTab(self.classification, "")
        self.molecularSpace = QtWidgets.QWidget()
        self.molecularSpace.setObjectName("molecularSpace")
        self.tabWidget.addTab(self.molecularSpace, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Molecule"))
        self.label_7.setText(_translate("MainWindow", "Input type"))
        self.label_2.setText(_translate("MainWindow", "Molecule"))
        self.drawButton.setText(_translate("MainWindow", "Draw Molecule"))
        self.analyzeButton.setText(_translate("MainWindow", "Analyze"))
        self.simButton.setText(_translate("MainWindow", "Similar Molecules"))
        self.label.setText(_translate("MainWindow", "Results"))
        self.wpCheckBox.setText(_translate("MainWindow", "Wrong prediction"))
        self.label_4.setText(_translate("MainWindow", "Input right labels"))
        self.cBox_1.setText(_translate("MainWindow", "Alcohol"))
        self.cBox_4.setText(_translate("MainWindow", "Amide"))
        self.cBox_7.setText(_translate("MainWindow", "Carboxylic acid"))
        self.cBox_10.setText(_translate("MainWindow", "Ether"))
        self.cBox_13.setText(_translate("MainWindow", "Lactame"))
        self.cBox_16.setText(_translate("MainWindow", "Oxygen heterocycle"))
        self.cBox_19.setText(_translate("MainWindow", "Thiol"))
        self.cBox_2.setText(_translate("MainWindow", "Aldehyde"))
        self.cBox_5.setText(_translate("MainWindow", "Aromatic"))
        self.cBox_8.setText(_translate("MainWindow", "Chiral"))
        self.cBox_11.setText(_translate("MainWindow", "Fused rings"))
        self.cBox_14.setText(_translate("MainWindow", "Metal-organic"))
        self.cBox_17.setText(_translate("MainWindow", "Sulfide"))
        self.cBox_20.setText(_translate("MainWindow", "Urea"))
        self.cBox_3.setText(_translate("MainWindow", "Alicycle"))
        self.cBox_6.setText(_translate("MainWindow", "Carbocycle"))
        self.cBox_9.setText(_translate("MainWindow", "Ester"))
        self.cBox_12.setText(_translate("MainWindow", "Ketone"))
        self.cBox_15.setText(_translate("MainWindow", "Nitrogen heterocycle"))
        self.cBox_18.setText(_translate("MainWindow", "Sulfur heterocycle"))
        self.label_10.setText(_translate("MainWindow", "Comments"))
        self.sendRightButton.setText(_translate("MainWindow", "Create report file"))
        self.label_8.setText(_translate("MainWindow", "Molecule Structure"))
        self.label_9.setText(_translate("MainWindow", "Similar Molecules"))
        self.label_5.setText(_translate("MainWindow", "Molecule information"))
        self.infoTable.setSortingEnabled(True)
        item = self.infoTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Property"))
        item = self.infoTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        self.label_3.setText(_translate("MainWindow", "Class probability"))
        item = self.confTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Class"))
        item = self.confTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Probability"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.classification), _translate("MainWindow", "Classification"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.molecularSpace), _translate("MainWindow", "Tab 2"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))

from QLabel_mod import QLabel_click
